name: Nuvama Daily Capital Flows Report

on:
  schedule:
    # Runs every day at 09:00 IST (03:30 UTC)
    - cron: "30 3 * * *"
  workflow_dispatch: {}   # Allow manual trigger from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run report downloader
        env:
          WEBSITE_USER: ${{ secrets.WEBSITE_USER }}
          WEBSITE_PASS: ${{ secrets.WEBSITE_PASS }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          ENABLE_EMAIL: ${{ secrets.ENABLE_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          python bot.py

      - name: Upload downloaded files
        uses: actions/upload-artifact@v4
        with:
          name: capital-flows-${{ github.run_id }}
          path: downloads/**
          if-no-files-found: warn
